name: send-issue-smartsheet
run-name: ${{ github.actor }} is testing this workflow
on:
  issues:
    types: [opened]

env:
  SMART_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Increment
        id: increment_issue_num
        uses: action-pack/increment@v2
        with:
          name: 'ISSUE_NUM'
          token: ${{ secrets.VAR_GH_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install smartsheet-python-sdk
          pip install python-dotenv

      - name: Fetch Data and Write to Sheet
        env:
          SMART_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          ISSUE_NUM: ${{ steps.increment_issue_num.outputs.new_value }}
        run: |
          python post-issue-smartsheet.py